on:
  pull_request:
    branches:
      - master

jobs:
  generate_test_files:
    runs-on: ubuntu-latest
    name: build the test files
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkout MOIA proto files
      uses: actions/checkout@v2
      with:
        repository: 'moia-dev/api'
        ref: 'master'
        path: 'test_files'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag moia/prototool:test && docker run -v $(pwd)/test_files:/work/test_files moia/prototool:test prototool generate test_files/api/trip/http_v5_12.proto

