on:
  pull_request:
    branches:
      - master

jobs:
  generate_test_files:
    runs-on: ubuntu-latest
    name: Generate artefacts from test files
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./ # Uses an action in the root directory
